#端口，路径
server:
  port: 9090
  servlet:
    context-path: /security

#数据库
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springsecurity?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root

#jpa
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

