#端口，路径
server:
  port: 9090
  servlet:
    context-path: /security

#数据库
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springsecurity?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root

  #jpa
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  #thymeleaf
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: utf-8
    servlet:
      content-type: text/html
    mode: LEGACYHTML5

  #redis
  redis:
    #数据库索引
    database: 0
    host: 118.25.153.58
    port: 6379
    password: echoredis
    jedis:
      pool:
        #最大连接数
        max-active: 8
        #阻塞等待时间,负数表示没限制
        max-wait: -1
        #最大空闲
        max-idle: 8
        #最小空闲
        min-idle: 0
    #连接超时时间
    timeout: 10000

#logback日志配置
logging:
  config: classpath:logback-spring.xml
